dist: xenial
sudo: true
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

matrix:
  include:
    - os: linux
      env:
        - CMAKE_FLAGS="-DENABLE_COVERAGE:BOOL=TRUE"
    - os: linux
      env:
        - CMAKE_FLAGS="-DENABLE_COVERAGE:BOOL=TRUE -DCPP_STARTER_USE_GOOGLE_TEST=ON"
    - os: linux
      before_install:
        - git clone https://github.com/catchorg/Catch2.git
        - cd Catch2
        - cmake -Bbuild -H. -DBUILD_TESTING=OFF
        - sudo env "PATH=$PATH" cmake --build build/ --target install
        - cd ..
      env:
        - CMAKE_FLAGS="-DENABLE_COVERAGE:BOOL=TRUE -DCPP_STARTER_USE_CATCH2=ON"

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake ${CMAKE_FLAGS} .
  - cmake --build . -- -j2 
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-7



