name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

# Use a bash shell so we can use the same syntax for environment variable
# access regardless of the host operating system
defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        cmake -S . -B ./build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build ./build --config $BUILD_TYPE

    - name: Test
      working-directory: ./build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
